using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ToDoList.Domain.Entities;

namespace ToDoList.Infrastructure.EF.Extensions
{
    internal static class EntityTypeBuilderExtensions
    {
        public static EntityTypeBuilder AddAutoGeneratedDates<TEntity, TIdentifier>(this EntityTypeBuilder<TEntity> builder)
            where TIdentifier
                : IComparable<TIdentifier>, IEquatable<TIdentifier>, new()
            where TEntity : Entity<TIdentifier>
        {
            builder.Property(e => e.CreatedAt)
                .ValueGeneratedOnAdd()
                .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);

            builder.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .IsConcurrencyToken()
                .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);

            return builder;
        }
    }
}
