using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ToDoList.Domain.Entities;
using ToDoList.Infrastructure.EF.Extensions;

namespace ToDoList.Infrastructure.EF.AppContext.Configuration
{
    public class EntityConfiguration<TEntity> : EntityConfiguration<TEntity, Guid>
        where TEntity : Entity<Guid>
    {
        public override void Configure(EntityTypeBuilder<TEntity> builder)
        {
            base.Configure(builder);

            builder.Property(e => e.Id)
                .ValueGeneratedNever()
                .IsRequired();

            builder.HasKey(e => e.Id);
        }
    }
    public class EntityConfiguration<TEntity, TIdentifier> : IEntityTypeConfiguration<TEntity>
        where TIdentifier
            : IComparable<TIdentifier>, IEquatable<TIdentifier>, new()
        where TEntity : Entity<TIdentifier>
    {
        public virtual void Configure(EntityTypeBuilder<TEntity> builder)
        {
            builder.AddAutoGeneratedDates<TEntity, TIdentifier>();
        }
    }
}
